--region PoC colorscheme - #ccc on #000 with ColorScheme autocmd for persistence
-- Applied after plugins load so it overrides everything.
-- Wrapped in a ColorScheme autocmd so highlights re-apply if a colorscheme
-- event fires (e.g., from a plugin or :colorscheme command).
local function apply_highlights()
  vim.cmd("highlight Normal guifg=#cccccc guibg=#000000")
  vim.cmd("highlight NormalFloat guifg=#cccccc guibg=#111111")
  vim.cmd("highlight FloatBorder guifg=#555555 guibg=#111111")
  vim.cmd("highlight CursorLine guibg=#111111")
  vim.cmd("highlight CursorLineNr guifg=#cccccc guibg=#111111")
  vim.cmd("highlight LineNr guifg=#555555")
  vim.cmd("highlight Visual guibg=#264f78")
  vim.cmd("highlight Search guifg=#000000 guibg=#cccccc")
  vim.cmd("highlight IncSearch guifg=#000000 guibg=#ffffff")
  vim.cmd("highlight StatusLine guifg=#cccccc guibg=#1a1a1a")
  vim.cmd("highlight StatusLineNC guifg=#555555 guibg=#0a0a0a")
  vim.cmd("highlight Pmenu guifg=#cccccc guibg=#1a1a1a")
  vim.cmd("highlight PmenuSel guifg=#ffffff guibg=#264f78")
  vim.cmd("highlight PmenuSbar guibg=#1a1a1a")
  vim.cmd("highlight PmenuThumb guibg=#555555")
  vim.cmd("highlight SignColumn guibg=#000000")
  vim.cmd("highlight Comment guifg=#555555 gui=italic")
  vim.cmd("highlight String guifg=#98c379")
  vim.cmd("highlight Keyword guifg=#c678dd")
  vim.cmd("highlight Function guifg=#61afef")
  vim.cmd("highlight Type guifg=#e5c07b")
  vim.cmd("highlight Number guifg=#d19a66")
  vim.cmd("highlight Operator guifg=#cccccc")
  vim.cmd("highlight Constant guifg=#d19a66")
  vim.cmd("highlight Identifier guifg=#cccccc")
  vim.cmd("highlight Statement guifg=#c678dd")
  vim.cmd("highlight PreProc guifg=#c678dd")
  vim.cmd("highlight Special guifg=#56b6c2")
  vim.cmd("highlight DiagnosticError guifg=#e06c75")
  vim.cmd("highlight DiagnosticWarn guifg=#e5c07b")
  vim.cmd("highlight DiagnosticInfo guifg=#61afef")
  vim.cmd("highlight DiagnosticHint guifg=#56b6c2")
  vim.cmd("highlight WinSeparator guifg=#333333 guibg=#000000")
  vim.cmd("highlight NeoTreeNormal guifg=#cccccc guibg=#0a0a0a")
  vim.cmd("highlight NeoTreeNormalNC guifg=#cccccc guibg=#0a0a0a")
  vim.cmd("highlight NeoTreeWinSeparator guifg=#333333 guibg=#000000")
  vim.cmd("highlight TelescopeNormal guifg=#cccccc guibg=#111111")
  vim.cmd("highlight TelescopeBorder guifg=#555555 guibg=#111111")
  vim.cmd("highlight TelescopePromptNormal guifg=#cccccc guibg=#1a1a1a")
  vim.cmd("highlight TelescopePromptBorder guifg=#555555 guibg=#1a1a1a")
  vim.cmd("highlight TelescopeResultsNormal guifg=#cccccc guibg=#111111")
  vim.cmd("highlight TelescopePreviewNormal guifg=#cccccc guibg=#0a0a0a")
end

-- Apply now and re-apply on any future ColorScheme event
apply_highlights()
vim.api.nvim_create_autocmd("ColorScheme", { callback = apply_highlights })
--endregion PoC colorscheme
